version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=attend_ON_dev
      - REACT_APP_WORD=World
    # env_file:
    #   - ./env