FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . . 

ENV REACT_APP_NAME=myName
ENV REACT_APP_WORD=country

RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html


