version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment:
      - REACT_APP_NAME=attend_ON_prod
      - REACT_APP_WORD=WORD
    # env_file:
    #   - ./env